✨ Initial test of file loading in web app
Demonstrate reading file contents in SPA using code defined in the client lib.

Also build fixes:

- simplify makefile a bit, and fail fast on ci failure
- fix lib not updating in child deps, i hope
- update everything to tsc 4.5 beta, required for exports block

huh why is spa flaky

- it looks like sometimes tsc decides to say:

> Error: [14:35:27] [@snowpack/plugin-typescript] src/App.tsx(5,33): error TS1471: Module '@opentdf/client/chunkers.js' cannot be imported using this construct. The specifier only resolves to an ES module, which cannot be imported synchronously. Use dynamic import instead.

Is this true? I'd rather have snowpack load everything into one file so I don't want this, right?

Also, why does it work locally (sometimes?)

Update package.json

Update package.json

Update web-test-runner.config.cjs

move check version into ci workflow file

make format

Update package.json

Create chunkers.spec.ts

Update package.json

ugh mauybe

roll back changes to tsc version

ugh doesn't fix it

trying

npm i

Update Makefile

Update .nvmrc

consolidating lint into CI

simplify app a bit